version: "3.9"
services:
  proxy:
    container_name: proxy
    build: ./docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
  app:
    container_name: photo-list-app
    ports:
      - 5173:5173
    build: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./src:/var/www/html
  db:
    container_name: photo-list-db
    build: ./docker/mysql
    ports: 
      - 3306:3306
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - photo-list-db-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: photo_list_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
volumes:
  photo-list-db-volume: